<?php

namespace Database\Seeders;

use App\Models\Monster;
use App\Models\MonsterStat;
use Illuminate\Database\Seeder;

class MonsterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Создание монстров...');

        $monsters = $this->getMonstersData();

        foreach ($monsters as $monsterData) {
            $monster = Monster::create([
                'name' => $monsterData['name'],
                'type' => $monsterData['type'],
                'level' => $monsterData['level'],
                'rank' => $monsterData['rank'],
                'faction_id' => null,
                'ai_behavior' => $monsterData['ai_behavior'],
                'respawn_time' => $monsterData['respawn_time'],
                'description' => $monsterData['description'],
                'is_active' => true,
            ]);

            MonsterStat::create([
                'monster_id' => $monster->id,
                'health_max' => $monsterData['stats']['health_max'],
                'mana_max' => $monsterData['stats']['mana_max'],
                'attack_power' => $monsterData['stats']['attack_power'],
                'magic_power' => $monsterData['stats']['magic_power'],
                'defense' => $monsterData['stats']['defense'],
                'magic_defense' => $monsterData['stats']['magic_defense'],
                'accuracy' => $monsterData['stats']['accuracy'],
                'magic_accuracy' => $monsterData['stats']['magic_accuracy'],
                'dodge' => $monsterData['stats']['dodge'],
                'critical_chance' => $monsterData['stats']['critical_chance'],
                'critical_power' => $monsterData['stats']['critical_power'],
                'experience_reward' => $monsterData['stats']['experience_reward'],
                'attack_type' => $monsterData['stats']['attack_type'],
            ]);
        }

        $this->command->info('Монстры успешно созданы!');
    }

    /**
     * Получить данные всех монстров.
     */
    private function getMonstersData(): array
    {
        return [
            // Лесные и полевые
            [
                'name' => 'Лесной тролль',
                'type' => 'humanoid',
                'level' => 5,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Большое глупое существо с дубиной. Нападает на всех, кто посмеет войти в его территорию.',
                'stats' => $this->generateStats(5, 'physical', 'normal'),
            ],
            [
                'name' => 'Ведьма болотная',
                'type' => 'humanoid',
                'level' => 8,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 15,
                'description' => 'Старая карга, живущая в хижине на болоте. Варит зелья и накладывает проклятия.',
                'stats' => $this->generateStats(8, 'magical', 'elite'),
            ],
            [
                'name' => 'Ядовитый паук',
                'type' => 'beast',
                'level' => 3,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 5,
                'description' => 'Крупный паук, плетущий липкие сети в чаще. Его укус парализует жертву.',
                'stats' => $this->generateStats(3, 'physical', 'normal'),
            ],
            [
                'name' => 'Старый дух леса',
                'type' => 'magical',
                'level' => 12,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 20,
                'description' => 'Древнее существо, защищающее свой лес. Может говорить с деревьями и животными.',
                'stats' => $this->generateStats(12, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Зараженный медведь',
                'type' => 'beast',
                'level' => 7,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 12,
                'description' => 'Огромный медведь с бешеным взглядом. Нападает без страха и причины.',
                'stats' => $this->generateStats(7, 'physical', 'normal'),
            ],
            [
                'name' => 'Бешеный кабан',
                'type' => 'beast',
                'level' => 2,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 5,
                'description' => 'Агрессивный секач с острыми клыками. Атакует, заряжаясь с опущенной головой.',
                'stats' => $this->generateStats(2, 'physical', 'normal'),
            ],
            [
                'name' => 'Гигантская оса',
                'type' => 'beast',
                'level' => 4,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 8,
                'description' => 'Летающее насекомое размером с собаку. Её жало содержит смертельный яд.',
                'stats' => $this->generateStats(4, 'physical', 'normal'),
            ],
            [
                'name' => 'Волк-оборотень',
                'type' => 'beast',
                'level' => 10,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'В полнолуние этот монстр покидает человеческое обличье и становится огромным волком.',
                'stats' => $this->generateStats(10, 'physical', 'elite'),
            ],
            [
                'name' => 'Грибной тролль',
                'type' => 'humanoid',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Покрытый спорами тролль, который ударами своей дубины отравляет противников.',
                'stats' => $this->generateStats(6, 'hybrid', 'normal'),
            ],
            [
                'name' => 'Лесной разбойник',
                'type' => 'humanoid',
                'level' => 4,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 8,
                'description' => 'Бандит, который прячется в засаде среди деревьев и грабит путников.',
                'stats' => $this->generateStats(4, 'physical', 'normal'),
            ],
            [
                'name' => 'Ворон-убийца',
                'type' => 'beast',
                'level' => 3,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 5,
                'description' => 'Стая огромных воронов, способных заклевать до костей за минуту.',
                'stats' => $this->generateStats(3, 'physical', 'normal'),
            ],
            [
                'name' => 'Дикий вепрь',
                'type' => 'beast',
                'level' => 3,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 5,
                'description' => 'Крупный и злой зверь, который яростно защищает свою территорию.',
                'stats' => $this->generateStats(3, 'physical', 'normal'),
            ],
            [
                'name' => 'Ядовитый плющ',
                'type' => 'magical',
                'level' => 5,
                'rank' => 'normal',
                'ai_behavior' => 'neutral',
                'respawn_time' => 10,
                'description' => 'Растение-ловушка, которое опутывает жертву ветвями и выделяет парализующий сок.',
                'stats' => $this->generateStats(5, 'magical', 'normal'),
            ],
            [
                'name' => 'Болотная гадюка',
                'type' => 'beast',
                'level' => 4,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 8,
                'description' => 'Змея, маскирующаяся в тине. Её яд вызывает мучительную смерть.',
                'stats' => $this->generateStats(4, 'physical', 'normal'),
            ],
            [
                'name' => 'Лесной призрак',
                'type' => 'undead',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Дух путника, заблудившегося и погибшего в лесу. Заманивает других в чащу.',
                'stats' => $this->generateStats(6, 'magical', 'normal'),
            ],
            [
                'name' => 'Голодный волк',
                'type' => 'beast',
                'level' => 3,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 5,
                'description' => 'Отощавший, но опасный хищник, который охотится стаей даже днём.',
                'stats' => $this->generateStats(3, 'physical', 'normal'),
            ],
            [
                'name' => 'Большой паук-охотник',
                'type' => 'beast',
                'level' => 5,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Не плетёт сетей, а преследует добычу в траве, набрасываясь из засады.',
                'stats' => $this->generateStats(5, 'physical', 'normal'),
            ],
            [
                'name' => 'Разъяренный лось',
                'type' => 'beast',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Величественное животное, которое в период гона атакует любого, кто к нему приблизится.',
                'stats' => $this->generateStats(6, 'physical', 'normal'),
            ],
            [
                'name' => 'Болотный житель',
                'type' => 'humanoid',
                'level' => 7,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 12,
                'description' => 'Покрытое тиной и водорослями гуманоидное существо, таскающее жертв на дно.',
                'stats' => $this->generateStats(7, 'physical', 'normal'),
            ],
            [
                'name' => 'Лесной дух',
                'type' => 'magical',
                'level' => 9,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 15,
                'description' => 'Безобидное с виду существо, но если разгневать его — деревья сами начнут атаковать.',
                'stats' => $this->generateStats(9, 'hybrid', 'elite'),
            ],

            // Горные и пещерные
            [
                'name' => 'Пещерный тролль',
                'type' => 'humanoid',
                'level' => 8,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Мохнатый тролль, живущий в темноте. Плохо видит, но имеет отличный слух.',
                'stats' => $this->generateStats(8, 'physical', 'normal'),
            ],
            [
                'name' => 'Каменный голем',
                'type' => 'elemental',
                'level' => 15,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 30,
                'description' => 'Древний страж гор, собранный из валунов. Неуклюжий, но очень сильный.',
                'stats' => $this->generateStats(15, 'physical', 'elite'),
            ],
            [
                'name' => 'Снежный горный волк',
                'type' => 'beast',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Белый как снег волк, чья стая нападает на путников в горах.',
                'stats' => $this->generateStats(6, 'physical', 'normal'),
            ],
            [
                'name' => 'Пещерная тварь',
                'type' => 'beast',
                'level' => 7,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 12,
                'description' => 'Слепое аморфное существо, ориентирующееся по запаху и вибрациям.',
                'stats' => $this->generateStats(7, 'physical', 'normal'),
            ],
            [
                'name' => 'Скальный червь',
                'type' => 'beast',
                'level' => 12,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Гигантский червь, прорывающий ходы в камне. Нападает из-под ног.',
                'stats' => $this->generateStats(12, 'physical', 'elite'),
            ],
            [
                'name' => 'Ледяной призрак',
                'type' => 'undead',
                'level' => 10,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Дух замерзшего путника. Его прикосновение замораживает кровь.',
                'stats' => $this->generateStats(10, 'magical', 'elite'),
            ],
            [
                'name' => 'Горный орёл-убийца',
                'type' => 'beast',
                'level' => 9,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Исполинская птица, которая пикирует на добычу с огромной высоты.',
                'stats' => $this->generateStats(9, 'physical', 'normal'),
            ],
            [
                'name' => 'Пещерный крикун',
                'type' => 'beast',
                'level' => 5,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Летучая мышь с пронзительным криком, оглушающим жертву.',
                'stats' => $this->generateStats(5, 'magical', 'normal'),
            ],
            [
                'name' => 'Лавовый краб',
                'type' => 'elemental',
                'level' => 11,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Членистоногое размером с телегу, с панцирем, раскалённым как лава.',
                'stats' => $this->generateStats(11, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Горный гоблин',
                'type' => 'humanoid',
                'level' => 4,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 8,
                'description' => 'Юркое и трусливое существо, которое атакует камнями из-за укрытий.',
                'stats' => $this->generateStats(4, 'physical', 'normal'),
            ],
            [
                'name' => 'Снежный йети',
                'type' => 'humanoid',
                'level' => 18,
                'rank' => 'boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 60,
                'description' => 'Легендарный огромный гуманоид, покрытый белой шерстью. Крайне агрессивен.',
                'stats' => $this->generateStats(18, 'physical', 'boss'),
            ],
            [
                'name' => 'Подземный паук',
                'type' => 'beast',
                'level' => 7,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 12,
                'description' => 'Паук-одиночка, который маскируется под сталактит на потолке пещеры.',
                'stats' => $this->generateStats(7, 'physical', 'normal'),
            ],
            [
                'name' => 'Каменная гончая',
                'type' => 'elemental',
                'level' => 10,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Статуя пса, оживлённая магией. Неутомимо преследует свою цель.',
                'stats' => $this->generateStats(10, 'physical', 'elite'),
            ],
            [
                'name' => 'Пещерный скорпион',
                'type' => 'beast',
                'level' => 8,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Скорпион с ядовитым жалом, который светится в темноте.',
                'stats' => $this->generateStats(8, 'physical', 'normal'),
            ],
            [
                'name' => 'Ледяной элементаль',
                'type' => 'elemental',
                'level' => 13,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Живое воплощение стужи. Всё, чего он касается, покрывается льдом.',
                'stats' => $this->generateStats(13, 'magical', 'elite'),
            ],
            [
                'name' => 'Горный дух',
                'type' => 'magical',
                'level' => 14,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 30,
                'description' => 'Хранитель горных вершин. Наказывает тех, кто добывает руду без разрешения.',
                'stats' => $this->generateStats(14, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Пещерный летун',
                'type' => 'beast',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Агрессивная летучая мышь с острыми как бритва когтями.',
                'stats' => $this->generateStats(6, 'physical', 'normal'),
            ],
            [
                'name' => 'Скальный страж',
                'type' => 'elemental',
                'level' => 16,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 35,
                'description' => 'Неподвижный голем, который «оживает», если кто-то потревожит его покой.',
                'stats' => $this->generateStats(16, 'physical', 'elite'),
            ],
            [
                'name' => 'Холодный призрак',
                'type' => 'undead',
                'level' => 11,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Похож на ледяной туман. Вызывает сонливость и вечный сон в стуже.',
                'stats' => $this->generateStats(11, 'magical', 'elite'),
            ],
            [
                'name' => 'Глубинный червь',
                'type' => 'beast',
                'level' => 9,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Младший, но более быстрый и многочисленный родственник скального червя.',
                'stats' => $this->generateStats(9, 'physical', 'normal'),
            ],

            // Нежить
            [
                'name' => 'Скелет-воин',
                'type' => 'undead',
                'level' => 5,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Ожившие кости павшего солдата. Вооружён мечом и щитом, но очень хрупок.',
                'stats' => $this->generateStats(5, 'physical', 'normal'),
            ],
            [
                'name' => 'Болотный зомби',
                'type' => 'undead',
                'level' => 4,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 8,
                'description' => 'Разлагающийся труп, поднятый болотной магией. Медленный, но ядовитый.',
                'stats' => $this->generateStats(4, 'physical', 'normal'),
            ],
            [
                'name' => 'Призрак замка',
                'type' => 'undead',
                'level' => 8,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Бесплотный дух, обречённый вечно бродить по руинам своего дома.',
                'stats' => $this->generateStats(8, 'magical', 'normal'),
            ],
            [
                'name' => 'Оживший мертвец',
                'type' => 'undead',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Более свежий труп, чем зомби. Сохранил часть силы, что была при жизни.',
                'stats' => $this->generateStats(6, 'physical', 'normal'),
            ],
            [
                'name' => 'Вампир-кровосос',
                'type' => 'undead',
                'level' => 12,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Изящный и быстрый охотник, который высасывает жизнь из жертв.',
                'stats' => $this->generateStats(12, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Скелет-лучник',
                'type' => 'undead',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Кости лучника, которые метко стреляют из костяного лука.',
                'stats' => $this->generateStats(6, 'physical', 'normal'),
            ],
            [
                'name' => 'Блуждающий дух',
                'type' => 'undead',
                'level' => 7,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 12,
                'description' => 'Бесцельно скитающаяся душа. Её прикосновение вытягивает жизненные силы.',
                'stats' => $this->generateStats(7, 'magical', 'normal'),
            ],
            [
                'name' => 'Проклятый рыцарь',
                'type' => 'undead',
                'level' => 14,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 30,
                'description' => 'Рыцарь в полных доспехах, чья душа проклята служить злу.',
                'stats' => $this->generateStats(14, 'physical', 'elite'),
            ],
            [
                'name' => 'Могильный червь',
                'type' => 'undead',
                'level' => 5,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Червь-падальщик, выросший на нечистом грунте кладбища.',
                'stats' => $this->generateStats(5, 'physical', 'normal'),
            ],
            [
                'name' => 'Безголовый всадник',
                'type' => 'undead',
                'level' => 11,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Призрак всадника, разыскивающий свою потерянную голову.',
                'stats' => $this->generateStats(11, 'physical', 'elite'),
            ],
            [
                'name' => 'Кладбищенский страж',
                'type' => 'undead',
                'level' => 16,
                'rank' => 'boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 60,
                'description' => 'Мощный зомби, «сотканный» из десятков тел, охраняющий вход в склеп.',
                'stats' => $this->generateStats(16, 'physical', 'boss'),
            ],
            [
                'name' => 'Костяной маг',
                'type' => 'undead',
                'level' => 13,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Скелет мага, способный кидать простые, но мощные заклинания некромантии.',
                'stats' => $this->generateStats(13, 'magical', 'elite'),
            ],
            [
                'name' => 'Призрачный лучник',
                'type' => 'undead',
                'level' => 9,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Дух лучника, чьи стрелы не причиняют физического урона, но ранят душу.',
                'stats' => $this->generateStats(9, 'magical', 'normal'),
            ],
            [
                'name' => 'Ночной упырь',
                'type' => 'undead',
                'level' => 10,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Летающий труп, который наводит ужас одним своим видом и воем.',
                'stats' => $this->generateStats(10, 'magical', 'elite'),
            ],
            [
                'name' => 'Восставший из могилы',
                'type' => 'undead',
                'level' => 3,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 5,
                'description' => 'Простой фермер или горожанин, поднятый как бессмысленный зомби.',
                'stats' => $this->generateStats(3, 'physical', 'normal'),
            ],
            [
                'name' => 'Теневой вор',
                'type' => 'undead',
                'level' => 8,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Призрак, который не атакует в лоб, а высасывает силы из тени жертвы.',
                'stats' => $this->generateStats(8, 'magical', 'normal'),
            ],
            [
                'name' => 'Костяной голем',
                'type' => 'undead',
                'level' => 15,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 30,
                'description' => 'Голем, собранный из костей множества существ. Силён и живуч.',
                'stats' => $this->generateStats(15, 'physical', 'elite'),
            ],
            [
                'name' => 'Призрачный воин',
                'type' => 'undead',
                'level' => 12,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Более мощная версия призрака, сохранившая боевые навыки и носящая доспехи.',
                'stats' => $this->generateStats(12, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Некромант',
                'type' => 'humanoid',
                'level' => 20,
                'rank' => 'boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 60,
                'description' => 'Живой чародей, приказывающий нежити. Главная цель — уничтожить его первым.',
                'stats' => $this->generateStats(20, 'magical', 'boss'),
            ],
            [
                'name' => 'Древний лич',
                'type' => 'undead',
                'level' => 25,
                'rank' => 'world_boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 120,
                'description' => 'Могущественный некромант, добившийся бессмертия. Очень опасный противник.',
                'stats' => $this->generateStats(25, 'magical', 'world_boss'),
            ],

            // Магические и редкие
            [
                'name' => 'Огненный элементаль',
                'type' => 'elemental',
                'level' => 12,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Живой сгусток пламени. Поджигает всё, к чему прикасается.',
                'stats' => $this->generateStats(12, 'magical', 'elite'),
            ],
            [
                'name' => 'Ледяной дух',
                'type' => 'elemental',
                'level' => 11,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Существо из вечной мерзлоты. Создает наледи и метает ледяные осколки.',
                'stats' => $this->generateStats(11, 'magical', 'elite'),
            ],
            [
                'name' => 'Электрический сгусток',
                'type' => 'elemental',
                'level' => 10,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 20,
                'description' => 'Шаровая молния, которая перемещается хаотично и бьёт разрядами.',
                'stats' => $this->generateStats(10, 'magical', 'elite'),
            ],
            [
                'name' => 'Магический голем',
                'type' => 'magical',
                'level' => 14,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 30,
                'description' => 'Голем, созданный чистой магией. Устойчив к заклинаниям.',
                'stats' => $this->generateStats(14, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Иллюзорный двойник',
                'type' => 'magical',
                'level' => 8,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Копия одного из игроков, созданная магией подземелья. Имеет часть способностей оригинала.',
                'stats' => $this->generateStats(8, 'hybrid', 'normal'),
            ],
            [
                'name' => 'Древний дух',
                'type' => 'magical',
                'level' => 16,
                'rank' => 'boss',
                'ai_behavior' => 'neutral',
                'respawn_time' => 60,
                'description' => 'Дух природы, наделённый великой силой. Может быть как защитником, так и карателем.',
                'stats' => $this->generateStats(16, 'hybrid', 'boss'),
            ],
            [
                'name' => 'Хаос-волк',
                'type' => 'magical',
                'level' => 9,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Волк с мехом, переливающимся всеми цветами радуги. Его укус вызывает случайные магические эффекты.',
                'stats' => $this->generateStats(9, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Магический кристалл',
                'type' => 'magical',
                'level' => 7,
                'rank' => 'normal',
                'ai_behavior' => 'neutral',
                'respawn_time' => 12,
                'description' => 'Оживший минерал, стреляющий сконцентрированными лучами энергии.',
                'stats' => $this->generateStats(7, 'magical', 'normal'),
            ],
            [
                'name' => 'Огненная птица',
                'type' => 'magical',
                'level' => 15,
                'rank' => 'boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 60,
                'description' => 'Феникс, который, погибая, возрождается из пела, если не потушить пламя.',
                'stats' => $this->generateStats(15, 'magical', 'boss'),
            ],
            [
                'name' => 'Ледяной голем',
                'type' => 'elemental',
                'level' => 13,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Голем изо льда. В ближнем бою может заморозить противника.',
                'stats' => $this->generateStats(13, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Энергетический сгусток',
                'type' => 'elemental',
                'level' => 9,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 15,
                'description' => 'Безформенное существо, питающееся маной. Атакует электрическими разрядами.',
                'stats' => $this->generateStats(9, 'magical', 'normal'),
            ],
            [
                'name' => 'Магический фамилиар',
                'type' => 'magical',
                'level' => 6,
                'rank' => 'normal',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 10,
                'description' => 'Дух-слуга, призванный магом для защиты. Может быть невидимым.',
                'stats' => $this->generateStats(6, 'magical', 'normal'),
            ],
            [
                'name' => 'Зачарованный доспех',
                'type' => 'magical',
                'level' => 10,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 20,
                'description' => 'Пустые доспехи, анимированные магией. Охраняют сокровищницы.',
                'stats' => $this->generateStats(10, 'physical', 'elite'),
            ],
            [
                'name' => 'Волшебный дракон',
                'type' => 'magical',
                'level' => 22,
                'rank' => 'boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 90,
                'description' => 'Небольшой, но очень умный дракон, владеющий магией воздуха.',
                'stats' => $this->generateStats(22, 'magical', 'boss'),
            ],
            [
                'name' => 'Магический щит',
                'type' => 'magical',
                'level' => 8,
                'rank' => 'normal',
                'ai_behavior' => 'neutral',
                'respawn_time' => 15,
                'description' => 'Летающий щит, который атакует тараном и защищает других существ.',
                'stats' => $this->generateStats(8, 'physical', 'normal'),
            ],
            [
                'name' => 'Огненный демон',
                'type' => 'demon',
                'level' => 18,
                'rank' => 'boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 60,
                'description' => 'Существо из другого мира, тело которого состоит из раскалённой лавы.',
                'stats' => $this->generateStats(18, 'hybrid', 'boss'),
            ],
            [
                'name' => 'Ледяная ведьма',
                'type' => 'humanoid',
                'level' => 17,
                'rank' => 'boss',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 60,
                'description' => 'Владычица холода, способная заморозить противника одним взглядом.',
                'stats' => $this->generateStats(17, 'magical', 'boss'),
            ],
            [
                'name' => 'Электрический элементаль',
                'type' => 'elemental',
                'level' => 12,
                'rank' => 'elite',
                'ai_behavior' => 'aggressive',
                'respawn_time' => 25,
                'description' => 'Существо из чистой энергии, оставляющее после себя запах озона.',
                'stats' => $this->generateStats(12, 'magical', 'elite'),
            ],
            [
                'name' => 'Магический страж',
                'type' => 'magical',
                'level' => 11,
                'rank' => 'elite',
                'ai_behavior' => 'neutral',
                'respawn_time' => 20,
                'description' => 'Автоматическая конструкция, созданная для охраны магических мест.',
                'stats' => $this->generateStats(11, 'hybrid', 'elite'),
            ],
            [
                'name' => 'Древний голем',
                'type' => 'elemental',
                'level' => 20,
                'rank' => 'boss',
                'ai_behavior' => 'neutral',
                'respawn_time' => 90,
                'description' => 'Голем, простоявший тысячелетия. Его тело покрыто рунами и мхом.',
                'stats' => $this->generateStats(20, 'hybrid', 'boss'),
            ],
        ];
    }

    /**
     * Генерировать статистики для монстра на основе уровня и типа.
     */
    private function generateStats(int $level, string $attackType, string $rank): array
    {
        $multiplier = match ($rank) {
            'normal' => 1.0,
            'elite' => 1.5,
            'boss' => 2.5,
            'world_boss' => 4.0,
            default => 1.0,
        };

        $baseHealth = 100 + ($level * 20);
        $baseMana = 50 + ($level * 10);
        $baseAttack = 10 + ($level * 3);
        $baseMagic = 5 + ($level * 2);
        $baseDefense = 5 + ($level * 2);
        $baseMagicDefense = 5 + ($level * 2);

        // Корректировка в зависимости от типа атаки
        if ($attackType === 'physical') {
            $baseMagic = (int) ($baseMagic * 0.5);
        } elseif ($attackType === 'magical') {
            $baseAttack = (int) ($baseAttack * 0.5);
        }

        return [
            'health_max' => (int) ($baseHealth * $multiplier),
            'mana_max' => (int) ($baseMana * $multiplier),
            'attack_power' => (int) ($baseAttack * $multiplier),
            'magic_power' => (int) ($baseMagic * $multiplier),
            'defense' => (int) ($baseDefense * $multiplier),
            'magic_defense' => (int) ($baseMagicDefense * $multiplier),
            'accuracy' => min(95.0, 60.0 + ($level * 2)),
            'magic_accuracy' => min(95.0, 60.0 + ($level * 2)),
            'dodge' => min(30.0, 5.0 + ($level * 1.5)),
            'critical_chance' => min(25.0, 5.0 + ($level * 0.8)),
            'critical_power' => 1.5 + ($level * 0.05),
            'experience_reward' => (int) (($level * 10) * $multiplier),
            'attack_type' => $attackType,
        ];
    }
}
